package models

// Websocket types
const (
	NEW_DAEMON  = "NEW_DAEMON"
	ALL_DAEMONS = "ALL_DAEMONS"
	DAEMON_LEFT = "DAEMON_LEFT"

	CURRENT_CHECKS = "CURRENT_CHECKS"
	START_CHECKS   = "START_CHECKS"
	STOP_CHECKS    = "STOP_CHECKS"
	CHECK_RESULTS  = "CHECK_RESULTS"
)

// Check types
const (
	MASTER_API_CHECK        = "MASTER_API_CHECK"
	DNS_NSLOOKUP_KUBERNETES = "DNS_NSLOOKUP_KUBERNETES"
	DNS_SERVICE_NODE        = "DNS_SERVICE_NODE"
	DNS_SERVICE_POD         = "DNS_SERVICE_POD"
	HTTP_POD_SERVICE_A_B    = "HTTP_POD_SERVICE_A_B"
	HTTP_POD_SERVICE_A_C    = "HTTP_POD_SERVICE_A_C"
	HTTP_HAPROXY            = "HTTP_HAPROXY"
	HTTP_SERVICE_ABC        = "HTTP_SERVICE_ABC"
	ETCD_HEALTH             = "ETCD_HEALTH"
)
